services:
  apache:
    labels:
      - traefik.enable=true
      - traefik.http.routers.djmarian-wp.entrypoints=web-secure
      - traefik.http.routers.djmarian-wp.rule=HostRegexp(`${TRAEFIK_FQDN:?}`)
      - traefik.http.services.djmarian-wp.loadbalancer.server.port=80
    networks:
      - traefik
      - default

networks:
  traefik:
    external: true
